### ISSUE TITLE
bootstrap.json file is missing

### ISSUE THREAD

**Issue by apremkumar** [krraghavan/extjs5-jasmine#2]
First of all, thank  you for the wonderful presentation and the example. I appreciate your time and effort. I am trying to run the sample application using Sencha Cmd 6. The application says bootstrap.json is missing. Without bootsrtap, I am not able to proceed anywhere. You might have missed it while commiting in github. Please make it available for everyone's sake. Thank you

**Comment by krraghavan** [comment]
I believe this file is generated by the build process. Also do take a look at sencha test. I think it'll be much easier to use than jasmine. Previously we didn't have a choice but to use the technique I outlined but now they've released it and we are also going to switch
Raghavan 

Please pardon my brevity and any typos as this mail is sent from my mobile device

**Comment by apremkumar** [comment]
Sure yeah I will take a look at Sencha Test. But sadly Sencha Test is not available as a GPL version. 

"Sencha Test is made available under Commercial License.
There is no open source license for Sencha Test."
Quoted from: https://www.sencha.com/legal/

Anyway I have run your code by forging a bootstrap.json myself. And have implemented it for ExtJS 6 with some modifications. Thanks for the example. It helped me a lot.
